# Generated by Django 5.0.6 on 2024-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('page', models.IntegerField(choices=[(1, 'HOME_PAGE'), (2, 'PROJECT')], unique=True, verbose_name='Page')),
            ],
            options={
                'verbose_name': 'banners',
                'verbose_name_plural': 'banners',
                'db_table': 'banners',
            },
        ),
    ]
