# Generated by Django 5.0.6 on 2024-08-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.IntegerField(choices=[(1, 'HOME_PAGE'), (2, 'PROJECT')], verbose_name='Page'),
        ),
    ]
