# Generated by Django 5.0.6 on 2024-08-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_banner_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Short desc')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Về chúng tôi',
                'verbose_name_plural': 'Về chúng tôi',
                'db_table': 'abouts',
            },
        ),
    ]
