# Generated by Django 5.0.6 on 2024-08-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/images'),
        ),
    ]
