# Generated by Django 5.0.6 on 2024-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_aboutme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(verbose_name='Icon')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Short desc')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Hoạt động (Item)',
                'verbose_name_plural': 'Hoạt động (Item)',
                'db_table': 'item_actions',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('item', models.ManyToManyField(blank=True, related_name='action', to='ui.itemaction', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Hoạt động',
                'verbose_name_plural': 'Hoạt động',
                'db_table': 'actions',
            },
        ),
    ]
