# Generated by Django 5.0.6 on 2024-08-27 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_itemaction_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='item',
        ),
        migrations.AddField(
            model_name='action',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='ui.itemaction', verbose_name='item'),
        ),
    ]
