# Generated by Django 5.0.6 on 2024-08-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_action_item_action_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='item',
        ),
        migrations.AddField(
            model_name='itemaction',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='ui.action'),
        ),
    ]
