# Generated by Django 5.0.6 on 2024-09-04 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_remove_action_item_itemaction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ItemProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='image')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('content', models.TextField(verbose_name='content')),
                ('activity', models.BooleanField(default=True, verbose_name='activity')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ui.project', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Dự án (Item)',
                'verbose_name_plural': 'Dự án (Item)',
                'db_table': 'item_projects',
            },
        ),
    ]
