# Generated by Django 5.0.6 on 2024-09-04 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_project_itemproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameItemRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Tuyển dụng (Item)',
                'verbose_name_plural': 'Tuyển dụng (Item)',
                'db_table': 'name_item_recruitment',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Tuyển dụng',
                'verbose_name_plural': 'Tuyển dụng',
                'db_table': 'recruitment',
            },
        ),
        migrations.CreateModel(
            name='ItemNameItemRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('content', models.CharField(max_length=255, verbose_name='name')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_item_recruitment', to='ui.nameitemrecruitment', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Tuyển dụng (Item in item)',
                'verbose_name_plural': 'Tuyển dụng (Item in item)',
                'db_table': 'item_name_item_recruitment',
            },
        ),
        migrations.AddField(
            model_name='nameitemrecruitment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='ui.recruitment', verbose_name='item'),
        ),
    ]
