# Generated by Django 5.0.6 on 2024-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_nameitemrecruitment_recruitment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnameitemrecruitment',
            name='content',
            field=models.CharField(max_length=255, verbose_name='content'),
        ),
    ]
