# Generated by Django 5.0.6 on 2024-09-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_nameitemrecruitment_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameitemrecruitment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
