# Generated by Django 5.0.6 on 2024-09-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_nameitemrecruitment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='ItemPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='image')),
                ('link', models.TextField(verbose_name='link')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_partner', to='ui.partner', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Đối tác (item)',
                'verbose_name_plural': 'Đối tác (item)',
                'db_table': 'item_partners',
            },
        ),
    ]
