# Generated by Django 5.0.6 on 2024-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_partner_itempartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproject',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
