# Generated by Django 5.0.6 on 2024-09-06 02:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_itemproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproject',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
