# Generated by Django 5.0.6 on 2024-09-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0017_alter_aboutme_content_alter_itemaction_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('status_contact', models.BooleanField(default=False, verbose_name='Status contact')),
            ],
            options={
                'verbose_name': 'Đăng ký nhận voucher',
                'verbose_name_plural': 'Đăng ký nhận voucher',
                'db_table': 'register_voucher',
            },
        ),
    ]
