# Generated by Django 4.2.6 on 2024-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_register_created_at_register_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
