# Generated by Django 4.2.6 on 2024-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_alter_recruitment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameitemrecruitment',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
