# Generated by Django 4.2.6 on 2024-09-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0021_nameitemrecruitment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnameitemrecruitment',
            name='show_job_list',
            field=models.BooleanField(default=False, verbose_name='Show at page job list'),
        ),
    ]
