# Generated by Django 5.0.6 on 2024-09-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_itemnameitemrecruitment_show_job_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AlterField(
            model_name='itemaction',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='itemproject',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AlterField(
            model_name='nameitemrecruitment',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
