# Generated by Django 5.0.6 on 2024-09-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_alter_aboutme_slug_alter_itemaction_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'db_table': 'areas',
            },
        ),
    ]
