# Generated by Django 5.0.6 on 2024-09-09 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('area', models.CharField(max_length=255, verbose_name='Area')),
                ('resume_cv', models.FileField(unique=True, upload_to='static/cv', verbose_name='Resume/CV')),
                ('application_letter', models.TextField(verbose_name='Application letter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_item_Recruitment', to='ui.nameitemrecruitment', verbose_name='recruitment')),
            ],
        ),
    ]
