# Generated by Django 5.0.6 on 2024-09-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name': 'Ứng tuyển', 'verbose_name_plural': 'Ứng tuyển'},
        ),
        migrations.AlterModelTable(
            name='apply',
            table='applies',
        ),
    ]
