# Generated by Django 5.0.6 on 2024-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_alter_apply_options_alter_apply_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status_contact',
            field=models.BooleanField(default=False, verbose_name='Status Contact'),
        ),
    ]
