# Generated by Django 5.0.6 on 2024-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0027_apply_status_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/media/static/images'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/media/static/images'),
        ),
        migrations.AlterField(
            model_name='itempartner',
            name='image',
            field=models.FileField(unique=True, upload_to='static/media/static/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='itemproject',
            name='image',
            field=models.FileField(unique=True, upload_to='static/media/static/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='image',
            field=models.FileField(unique=True, upload_to='static/media/static/images', verbose_name='image'),
        ),
    ]
