# Generated by Django 5.0.6 on 2024-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0040_alter_aboutme_image_alter_apply_resume_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume_cv',
            field=models.FileField(unique=True, upload_to='cv', verbose_name='Resume/CV'),
        ),
    ]
