# Generated by Django 5.1.4 on 2024-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0041_alter_apply_resume_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproject',
            name='image_detail',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='images', verbose_name='image'),
        ),
    ]
