# Generated by Django 5.1.4 on 2024-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0042_itemproject_image_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproject',
            name='image_detail',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='images', verbose_name='image_detail'),
        ),
    ]
