# Generated by Django 5.1.4 on 2024-12-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0043_alter_itemproject_image_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images', verbose_name='Image (Detail Page)'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images', verbose_name='Image (Home Page)'),
        ),
    ]
