# Generated by Django 5.1.4 on 2024-12-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0044_aboutme_image_detail_alter_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.IntegerField(choices=[(1, 'HOME_PAGE'), (2, 'PROJECT'), (3, 'RECRUITMENT'), (4, 'FIELD')], verbose_name='Page'),
        ),
    ]
